Update aegis

diff --git a/aegis b/aegis
--- a/aegis
+++ b/aegis
@@ -347,28 +347,27 @@ express_ipt_dna() { $DEBUG && debug "express_ipt_dna $*"
 process_directive() {
 # $1: IPSET / $2: FILE
   _NFO=0
-  if _cipset_copy_set $1; then _RET=0 # an ipset is already loaded
+  if _cipset_copy_set $1; then # an ipset is already loaded
     if [ -r "$2" ]; then
       if $_RELOAD_WTD; then _RELOAD=true
       elif _cipset_diff_set_file $1 $2 # checking if ipset and file are identical
         then _RELOAD=false; _NFO=$INFO_DIR__SAME
         else _RELOAD=true
       fi
-    else # no file
-      _RELOAD=false
-      _NFO=$INFO_DIR__MISS
+    elif $_RELOAD_WTD; then _NFO=$INFO_DIR__DEST; return 1 # no file, we want to destroy the loaded ipset
+    else _RELOAD=false # no file, we want to keep the loaded ipset
     fi
     if $_RELOAD; then # reload is asked for; so need to swap ipset
       _cipset_swap_set_file $1 $2
       _NFO=$INFO_DIR__SWAP
     else _NFO=$INFO_DIR__KEEP # else keeping existing ipset
     fi
-  elif [ -r "$2" ]; then _RET=0 # file exists, so creating ipset from it
+  elif [ -r "$2" ]; then # file exists, so creating ipset from it
       _cipset_create_set_file $1 $2
       _NFO=$INFO_DIR__LOAD
-  else _RET=1; _NFO=$INFO_DIR__DEST # no file
+  else _NFO=$INFO_DIR__MISS; return 1 # no file
   fi
-  return $_RET
+  return 0
 }
 
 shield_uprear() { $DEBUG && debug "|---> shield_uprear $*"
@@ -1061,8 +1060,9 @@ STA_WINET=16
 STA_TIF=32
 STA_TINET=64
 STA_IPT=128
-STA_NDOWN=256
-STA_OK=259
+STA_OIPT=256
+STA_NDOWN=512
+STA_OK=515
 
 STA_IF_WAN=1
 STA_IF_TUN=2
@@ -1083,9 +1083,8 @@ directive_status() {
       fi
     else _NFO=$INFO_DIR__MISS # loaded but no file
     fi
-  elif [ -r "$2" ]; then _RET=1 # file exists, but not loaded
-      _NFO=$INFO_DIR__LOAD
-  else _RET=1 # no file, not loaded
+  elif [ -r "$2" ]; then _RET=1; _NFO=$INFO_DIR__LOAD # file exists, but not loaded
+  else _RET=1; _NFO=$INFO_DIR__DEST # no file, not loaded
   fi
   return $_RET
 }
@@ -1161,11 +1160,13 @@ _status() { $DEBUG && debug "|---> _status"
     [ "$_OTUN" != "$_TUN" ] &&                                    _CK=$((_CK+STA_TIF))
     [ $((_DNA+DNA_TBW)) -ne 0 ] && [ "$_OTINET" != "$_TINET" ] && _CK=$((_CK+STA_TINET))
 
-    AIPTF=/tmp/aegis_aipt OIPTF=/tmp/aegis_oipt
-    express_ipt_dna "$INFO_FILE" >$OIPTF
-    echo "$_IPT" >$AIPTF
-    ! /usr/bin/diff -q $OIPTF $AIPTF >/dev/null &&                _CK=$((_CK+STA_IPT))
-    /bin/rm -rf $OIPTF; /bin/rm -rf $AIPTF
+    if [ $((_ONFO&STA_IPT_MASK)) -ne INFO_IPT_PBM ]; then         _CK=$((_CK+STA_OIPT))
+      AIPTF=/tmp/aegis_aipt OIPTF=/tmp/aegis_oipt
+      express_ipt_dna "$INFO_FILE" >$OIPTF
+      echo "$_IPT" >$AIPTF
+      ! /usr/bin/diff -q $OIPTF $AIPTF >/dev/null &&              _CK=$((_CK+STA_IPT))
+      /bin/rm -rf $OIPTF; /bin/rm -rf $AIPTF
+    fi
   elif [ $_DNA -gt $DNA_LOG ] || [ "$_IPT" ]; then                _CK=$((_CK+STA_NDOWN))
   fi
   
@@ -1216,141 +1217,82 @@ _status >/dev/null
     $EXT_DRIVE && [ $((_CK&CK_PM)) -eq 0 ] && echo -e "\033[31m- set: post-mount.sh is not set properly for $SC_NAME!\033[0m"
     if [ $((_CK&STA_DNA)) -ne 0 ]; then
        _parse_dir() { case "$1" in
-      #  "$INFO_DIR__SAME") ;;
          "$INFO_DIR__DIFF") echo -e "\033[31m- directives: $2 file changed since $SC_NAME was upreared!\033[0m";; # loaded != file
          "$INFO_DIR__MISS") echo -e "\033[31m- directives: $2 file is missing!\033[0m";; # loaded but no file
          "$INFO_DIR__LOAD") echo -e "\033[31m- directives: $2 file was created after $SC_NAME was upreared!\033[0m";; # file exists, but not loaded
        esac; }
-#      _ODIR=$((_ONFO_DIR>>INFO_DIR_SHIFT))
       _parse_dir $((_DIR>>(INFO_DIR_ALL+INFO_DIR_BL))) 'global blocklist'
-      _parse_dir $((_DIR>>(INFO_DIR_WAN+INFO_DIR_BL))) 'WAN blocklist'
-      _parse_dir $((_DIR>>(INFO_DIR_TUN+INFO_DIR_BL))) 'VPN blocklist'
+      _parse_dir $((_DIR>>(INFO_DIR_WAN+INFO_DIR_BL))) 'WAN specific blocklist'
+      _parse_dir $((_DIR>>(INFO_DIR_TUN+INFO_DIR_BL))) 'VPN specific blocklist'
       _parse_dir $((_DIR>>(INFO_DIR_ALL+INFO_DIR_WL))) 'global whitelist'
-      _parse_dir $((_DIR>>(INFO_DIR_WAN+INFO_DIR_WL))) 'WAN whitelist'
-      _parse_dir $((_DIR>>(INFO_DIR_TUN+INFO_DIR_WL))) 'VPN whitelist'
-
-#      [ $((_DNA&DNA_TWL)) -ne $((_ODNA&DNA_TWL)) ] && :;
+      _parse_dir $((_DIR>>(INFO_DIR_WAN+INFO_DIR_WL))) 'WAN specific whitelist'
+      _parse_dir $((_DIR>>(INFO_DIR_TUN+INFO_DIR_WL))) 'VPN specific whitelist'
     fi
     [ $((_CK&STA_WIF)) -ne 0 ] &&             echo -e "\033[31m- WAN: interface changed since $SC_NAME was upreared!\033[0m"
     [ $((_CK&STA_WINET)) -ne 0 ] &&           echo -e "\033[31m- WAN: network range changed since $SC_NAME was upreared!\033[0m"
     [ $((_CK&STA_TIF)) -ne 0 ] &&             echo -e "\033[31m- VPN: tunnel changed since $SC_NAME was upreared!\033[0m"
     [ $((_CKSTA_TINET)) -ne 0 ] &&            echo -e "\033[31m- VPN: tunnel range changed since $SC_NAME was upreared!\033[0m"
+    [ $((_CKSTA_OIPT)) -ne 0 ] &&             echo -e "\033[31m- iptables: $SC_NAME rules could not be set properly during last uprear!\033[0m"
     [ $((_CKSTA_IPT)) -ne 0 ] &&              echo -e "\033[31m- iptables: current $SC_NAME rules were modified since last uprear!\033[0m"
-
- 
-#    [ $((_PB&CK_IPS_BL)) -ne 0 ] &&  echo -e "\033[31m- ipset: no blocklist is set!\033[0m"
-#    [ $((_PB&CK_IPS_WL)) -ne 0 ] &&  echo -e "\033[31m- ipset: no whitelist is set!\033[0m"
-#    [ $((_PB&CK_IPT_CH)) -ne 0 ] &&  echo -e "\033[31m- iptables: shield chains are not right!\033[0m"
-#    [ $((_PB&CK_IPT_WAN_BP)) -ne 0 ] &&  echo -e "\033[31m- iptables: WAN network range bypass rules are not right!\033[0m"
-#    [ $((_PB&CK_IPT_TUN_BP)) -ne 0 ] &&  echo -e "\033[31m- iptables: VPN network range bypass rules are not right!\033[0m"
-#    [ $((_PB&CK_IPT_WL)) -ne 0 ] &&  echo -e "\033[31m- iptables: whitelist rules are not right!\033[0m"
-#    [ $((_PB&CK_IPT_TUN)) -ne 0 ] &&      echo -e "\033[31m- iptables: VPN tunnel IFO rules are corrupted!\033[0m"
-#    [ $((_PB&CK_IPT_WAN)) -ne 0 ] &&      echo -e "\033[31m- iptables: WAN interface IFO rules are corrupted!\033[0m"
-#    [ $((_PB&PB_IPT_WAN_MISS)) -ne 0 ] && echo -e "\033[31m- iptables: WAN interface ($WAN_IF) IFO rules are missing!\033[0m"
-#    [ $((_PB&PB_IPT_IFO)) -ne 0 ] &&      echo -e "\033[31m- iptables: Extra shield IFO rules were found (likely from an old interface)!\033[0m"
   fi
+  
+  [ $VERBOSE ] || _exit $_RETVAL
+  _OFROM=$((_ONFO&INFO_FROM_MASK))
+  _ODIR=$(((_ONFO>>INFO_DIR_SHIFT)&INFO_DIR_MASK))
+  _OIPT=$(((_ONFO>>INFO_IPT_SHIFT)&INFO_IPT_MASK))
+  _OLOGD=$(((_ONFO>>INFO_LOGD_SHIFT)&INFO_LOGD_MASK))
+  echo -ne '\033[1;36mDetailed status:\033[0m'
+  [ $((_IF&STA_IF_WAN)) -ne 0 ] && echo "- shield is active for WAN interface '$WAN_IF'."
+  [ $((_IF&STA_IF_TUN)) -ne 0 ] && echo "- shield is active for VPN tunnel '$TUN_IF'."
+  # dates
+  _gentimeforlist() [ -e "$1" ] && echo "- $2 directives generation time: $(/bin/date +'%Y-%m-%d %X' -r "$1")" \
+                                || echo "- no $2 directives were generated.";
+  echo "- Actual router time: $(/bin/date +'%Y-%m-%d %X')"
+  [ "$SRC_BL_CACHE" ] && echo "- sources cache directives update time: $(/bin/date +'%Y-%m-%d %X' -r $SRC_BL_CACHE)"
+  _gentimeforlist "$ALL_BL_FILE" "global blocklist"
+  _gentimeforlist "$WAN_BL_FILE" "WAN specific blocklist"
+  _gentimeforlist "$TUN_BL_FILE" "VPN specific blocklist"
+  _gentimeforlist "$ALL_WL_FILE" "global whitelist"
+  _gentimeforlist "$WAN_WL_FILE" "WAN specific whitelist"
+  _gentimeforlist "$TUN_WL_FILE" "VPN specific whitelist"
+  [ $((_CK&CK_FWS)) -ne 0 ] &&     echo "- set: firewall-start.sh is set for $SC_NAME."
+  [ $((_CK&CK_PM)) -ne 0 ] &&      echo "- set: post-mount.sh is set for $SC_NAME."
+  case "$_OFROM" in
+    $INFO_FROM_SC)  FROM="$SC_NAME script" ;;
+    $INFO_FROM_PM)  FROM="post-mount.sh" ;;
+    $INFO_FROM_FWS) FROM="firewall-start.sh" ;;
+  esac
+  echo "- shield was upreared from: $FROM @ $(/bin/date +'%Y-%m-%d %X' -r $INFO_FILE)"
+  _parse_odir() { case "$1" in
+    "$INFO_DIR__SAME") echo "- loaded $2 directives were already identical to the ones to load.";;
+    "$INFO_DIR__KEEP") echo "! loaded $2 directives were kept as new ones could not be found!";;
+    "$INFO_DIR__LOAD") echo "- $2 directives were loaded.";;
+    "$INFO_DIR__SWAP") echo "- $2 directives were reloaded.";;
+    "$INFO_DIR__DEST") echo "- $2 directives were cleared.";;
+    "$INFO_DIR__MISS") echo "- no $2 directives were found.";;
+  esac; }
+  _parse_odir $((_DIR>>(INFO_DIR_ALL+INFO_DIR_BL))) 'global blocklist'
+  _parse_odir $((_DIR>>(INFO_DIR_WAN+INFO_DIR_BL))) 'WAN specific blocklist'
+  _parse_odir $((_DIR>>(INFO_DIR_TUN+INFO_DIR_BL))) 'VPN specific blocklist'
+  _parse_odir $((_DIR>>(INFO_DIR_ALL+INFO_DIR_WL))) 'global whitelist'
+  _parse_odir $((_DIR>>(INFO_DIR_WAN+INFO_DIR_WL))) 'WAN specific whitelist'
+  _parse_odir $((_DIR>>(INFO_DIR_TUN+INFO_DIR_WL))) 'VPN specific whitelist'
+  
+  if  [ $((_OIPT&INFO_IPT_KEEP)) -ne 0 ]; then echo "- iptables: rules were already set."
+  elif [ $((_OIPT&INFO_IPT_RUN)) -ne 0 ]; then echo "- iptables: rules were (re)set."
+  else echo "! iptables: rules were UNSUCCESSFULLY (re)set!"; fi
+  # _ODNA
+  
+  case "$INFO_LOGD" in
+    $INFO_LOGD_KEEP_OFF) echo '- log daemon: was already off.';;
+    $INFO_LOGD_KEEP_ON)  echo '- log daemon: was already on.';;
+    $INFO_LOGD_STOPPED)  echo '- log daemon: was turned off.';;
+    $INFO_LOGD_STARTED)  echo '- log daemon: was turned on.';;
+  esac
   
   _exit $_RETVAL
-  
-  
-  if [ $((_CK+_PB)) -ne 0 ] && [ $_WN -ne 0 ]; then
-    echo -ne '\033[1;35mWarnings:\033[0m'; [ 0$VERBOSE -ge 2 ] && echo " (CODE: $_WN)" || echo ''
-    case "$((_WN&WN_BL_FILE_NTLD))" in
-      $WN_BL_FILE_DIFF) echo -e "\033[35m- directives: shield blocklist is different than file.\033[0m";;
-      $WN_BL_FILE_MISS) echo -e "\033[35m- directives: shield blocklist is set but file is missing.\033[0m";;
-      $WN_BL_FILE_NTLD) echo -e "\033[35m- directives: no shield blocklist is set but file exists.\033[0m";;
-    esac
-    case "$((_WN&WN_WL_FILE_NTLD))" in
-      $WN_WL_FILE_DIFF) echo -e "\033[35m- directives: ipset whitelist set is different than file.\033[0m";;
-      $WN_WL_FILE_MISS) echo -e "\033[35m- directives: ipset whitelist is set but file is missing.\033[0m";;
-      $WN_WL_FILE_NTLD) echo -e "\033[35m- directives: no ipset whitelist is set but file exists.\033[0m";;
-    esac
-    [ $((_WN&CK_IPT_WAN_BP)) -ne 0 ] && echo -e "\033[31m- iptables: WAN network range bypass rules are missing!\033[0m"
-    [ "$TUN_IF" ] && [ $((_WN&CK_IPT_TUN_BP)) -ne 0 ] && echo -e "\033[31m- iptables: VPN network range bypass rules are missing!\033[0m"
-    [ $((_WN&WN_TUN_MISS)) -ne 0 ] && echo -e "\033[31m- iptables: VPN tunnel ($TUN_IF) IFO rules are missing!\033[0m"
-    [ $((_WN&WN_LOG_DIFF)) -ne 0 ] && echo -e "\033[35m- current logging settings differs from last time shield was upreared.\033[0m"
-  fi
  
-  [ $VERBOSE ] || return 0
-
-  echo -ne '\033[1;36mDetailed status:\033[0m'; [ 0$VERBOSE -ge 2 ] && echo " (CODE: $_CK)" || echo ''
-  echo "- Active WAN interface is '$WAN_IF'."
-  [ "$TUN_IF" ] && echo "- Active VPN tunnel is '$TUN_IF'." || echo "- no VPN tunnel found."
-  # dates
-  echo "- Actual router time: $(/bin/date +'%Y-%m-%d %X')"
-  [ -e "$SRC_BL_CACHE" ] && echo "- Sources cache directives update time: $(/bin/date +'%Y-%m-%d %X' -r $SRC_BL_CACHE)"
-  [ -e "$BL_FILE" ] && echo "- Blocklist directives generation time: $(/bin/date +'%Y-%m-%d %X' -r $BL_FILE)"
-  [ -e "$WL_FILE" ] && echo "- Whitelist directives generation time: $(/bin/date +'%Y-%m-%d %X' -r $WL_FILE)"
-  if [ $_CK -ne 0 ]; then
-    [ $((_CK&CK_FWS)) -ne 0 ] &&        echo "- set: firewall-start.sh is set for $SC_NAME."
-    [ $((_CK&CK_PM)) -ne 0 ] &&         echo "- set: post-mount.sh is set for $SC_NAME."
-    [ $((_CK&CK_IPS_BL)) -ne 0 ] &&     echo "- ipset: blocklist is set."
-    [ $((_CK&CK_IPS_WL)) -ne 0 ] &&     echo "- ipset: whitelist is set."
-    [ $((_CK&CK_IPT_CH)) -ne 0 ] &&     echo "- iptables: shield chains are set."
-    [ $((_CK&CK_IPT_WAN_BP)) -ne 0 ] && echo "- iptables: WAN network range bypass rules are set."
-    [ $((_CK&CK_IPT_TUN_BP)) -ne 0 ] && echo "- iptables: VPN network range bypass rules are set."
-    [ $((_CK&CK_IPT_WL)) -ne 0 ] &&     echo "- iptables: whitelist rules are set."
-    [ $((_CK&CK_IPT_LOG)) -ne 0 ] &&    echo "- iptables: $SC_NAME logging rules are set."
-    [ $((_CK&CK_IPT_TUN)) -ne 0 ] &&    echo "- iptables: VPN tunnel IFO rules are set."
-    [ $((_CK&CK_IPT_WAN)) -ne 0 ] &&    echo "- iptables: WAN interface IFO rules are set."
-  fi
-  
-  [ 0$VERBOSE -lt 2 ] && return 0
-
-  # Status file
-  echo -ne "\033[1;36mLast shield uprear report:\033[0m"
-  if [ -r "$INFO_FILE" ]; then
-    read INFO INFO_WAN INFO_TUN<"$INFO_FILE"
-    INFO_FROM=$((INFO&INFO_FROM_MASK))
-    INFO_IPS=$(((INFO>>INFO_IPS_SHIFT)&INFO_IPS_MASK))
-    INFO_IPT=$(((INFO>>INFO_IPT_SHIFT)&INFO_IPT_MASK))
-    INFO_LOGD=$(((INFO>>INFO_LOGD_SHIFT)&INFO_LOGD_MASK))
-    echo " (CODE: $INFO_FROM-$INFO_IPS-$INFO_IPT-$INFO_LOGD)"
-    case "$INFO_FROM" in
-      $INFO_FROM_SC) FROM="$SC_NAME script" ;;
-      $INFO_FROM_PM) FROM="post-mount.sh" ;;
-      $INFO_FROM_FWS) FROM="firewall-start.sh" ;;
-    esac
-    echo "- shield was upreared from: $FROM @ $(/bin/date +'%Y-%m-%d %X' -r $INFO_FILE)"
-    echo "- WAN interface was '$INFO_WAN'."
-    [ "$INFO_TUN" ] && echo "- VPN tunnel was '$INFO_TUN'." || echo '- No VPN tunnel was found.'
-    case $((INFO_IPS&INFO_IPS_BL_MASK)) in
-      0) echo '! directives: blocklist file was not found!' ;;
-      $INFO_IPS_BL_SAME) echo '- directives: ipset blocklist was already set and identical to file.' ;;
-      $INFO_IPS_BL_MISS) echo '- directives: blocklist file was not found! The one already in ipset was kept.' ;;
-      $INFO_IPS_BL_LOAD) echo '- directives: ipset blocklist was set from file.' ;;
-    esac
-    case $((INFO_IPS&INFO_IPS_WL_MASK)) in
-      0) echo '- directives: no whitelist file was found.' ;;
-      $((INFO_IPS_WL_SAME+INFO_IPS_WL_KEEP))) echo '- directives: ipset whitelist was already set and identical to file.' ;;
-      $INFO_IPS_WL_KEEP) echo '- directives: ipset whitelist was kept.' ;;
-      $INFO_IPS_WL_LOAD) echo '- directives: ipset whitelist was set from file.' ;;
-      $INFO_IPS_WL_SWAP) echo '- directives: ipset whitelist was updated from file.' ;;
-      $INFO_IPS_WL_DEL) echo '- directives: ipset whitelist was unset.' ;;
-    esac
-    if  [ $((INFO_IPT&INFO_IPT_KEEP)) -ne 0 ]; then echo "- iptables: rules were already set."; _P_IPT=true
-    elif [ $((INFO_IPT&INFO_IPT_RUN)) -ne 0 ]; then echo "- iptables: rules were (re)set."; _P_IPT=true
-    else _P_IPT=false; fi
-    if $_P_IPT; then
-      [ $((INFO_IPT&INFO_IPT_WIF)) -ne 0 ] && echo "- iptables: rules for WAN interface in place."
-      [ $((INFO_IPT&INFO_IPT_TIF)) -ne 0 ] && echo "- iptables: rules for VPN interface in place."
-      [ $((INFO_IPT&INFO_IPT_WIB)) -ne 0 ] && echo "- iptables: WAN network range bypass rules in place."
-      [ $((INFO_IPT&INFO_IPT_TIB)) -ne 0 ] && echo "- iptables: VPN network range bypass rules in place."
-      [ $((INFO_IPT&INFO_IPT_WL)) -ne 0 ]  && echo "- iptables: whitelist bypass rules in place."
-      [ $((INFO_IPT&INFO_IPT_LOG)) -ne 0 ] && echo "- iptables: logging rules in place."
-    else echo "! iptables: rules were UNSUCCESSFULLY (re)set!"; fi
  
-    case "$INFO_LOGD" in
-      $INFO_LOGD_KEEP_OFF) echo '- log daemon: was already off.';;
-      $INFO_LOGD_KEEP_ON)  echo '- log daemon: was already on.';;
-      $INFO_LOGD_STOPPED)  echo '- log daemon: was turned off.';;
-      $INFO_LOGD_STARTED)  echo '- log daemon: was turned on.';;
-    esac
-    
-    echo -ne "\033[0m"
-  else
-    echo -e '\n- No status file found.'
-  fi
   
   [ 0$VERBOSE -lt 3 ] && return 0
   
