Update aegis

diff --git a/aegis b/aegis
--- a/aegis
+++ b/aegis
@@ -659,12 +659,12 @@ upgrade() {
     if [ "$SC_LAST_VERS" ]; then
       _LOC_VERS=$(echo "$SC_VERS"|/bin/sed 's/[^[:digit:]]//g')
       _REM_VERS=$(echo "$SC_LAST_VERS"|/bin/sed 's/[^[:digit:]]//g')
-      if [ $_LOC_VERS -eq $_REM_VERS ]; then echo "- This is already the last version.            "; exit 0
+      if [ $_LOC_VERS -eq $_REM_VERS ]; then echo "- This is already the latest version.            "; exit 0
       elif [ $_LOC_VERS -lt $_REM_VERS ]; then echo "- New version available: $SC_LAST_VERS         "
       else echo -e "\033[35m- This version is higher than than the one available: $SC_LAST_VERS         \033[0m"
       fi
     else
-      >&2 echo -e "\033[31m! Could not check what is the last version online!\033[0m"
+      >&2 echo -e "\033[31m! Could not check what is the latest version online!\033[0m"
       exit 1
     fi
     UPGRADE_URL="$SC_MAIN_REPO/$SC_NAME"
@@ -976,11 +976,11 @@ info() {
   if [ "$SC_LAST_VERS" ]; then
     _LOC_VERS=$(echo "$SC_VERS"|/bin/sed 's/[^[:digit:]]//g')
     _REM_VERS=$(echo "$SC_LAST_VERS"|/bin/sed 's/[^[:digit:]]//g')
-    if [ $_LOC_VERS -eq $_REM_VERS ]; then echo "- This is the last version.            "
+    if [ $_LOC_VERS -eq $_REM_VERS ]; then echo "- This is the latest version.            "
     elif [ $_LOC_VERS -lt $_REM_VERS ]; then echo -e "\033[35m- New version available: $SC_LAST_VERS       \033[0m"
     else echo -e "\033[35m- This version is higher than than the one available: $SC_LAST_VERS       \033[0m"
     fi
-  else echo -e "\033[31m! Could not check what is the last version online!\033[0m"
+  else echo -e "\033[31m! Could not check what is the latest version online!\033[0m"
   fi
   if check_path
     then echo "- '$SC_NAME' is in PATH."
