Update aegis

diff --git a/aegis b/aegis
--- a/aegis
+++ b/aegis
@@ -2,12 +2,13 @@
 # ----------- ENVIRONMENT VARIABLES -----------
 # CAN BE SOURCED INTO UTILS USING AEGIS -------
 # USING: eval "$(aegis _env)" -----------------
-[ "$1" == '_env' ] && { /usr/bin/awk '$0==": ENV EOF"{exit} $0==": ENV STOP"{e=0} e{print} $0==": ENV START"{e=1}' $0; exit; }
+if [ "$1" == '_env' ]; then /usr/bin/awk '$0==": ENV EOF"{exit} $0==": ENV STOP"{e=0} e{print} $0==": ENV START"{e=1}' $0; exit; fi
 # ---------------------------------------------
 : ENV START
 # ---------------------------------------------
-command -v iptables>/dev/null 2>&1 || export PATH=/bin:/sbin:/usr/bin:/usr/sbin
-! command -v iprange>/dev/null 2>&1 && [ -e /root/.profile ] && source /root/.profile
+{
+! command -v iptables && export PATH=/bin:/sbin:/usr/bin:/usr/sbin
+! command -v iprange && [ -e /root/.profile ] && source /root/.profile
 SC_VERS="1.5.9"
 SC_NAME="aegis"
 SC_ABR="aegis"
@@ -26,15 +27,17 @@ INFO_FILE="/tmp/${SC_ABR}_status"
 LOG_FILE="/var/log/log-$SC_ABR"
 SHIELD_LOCK="/tmp/${SC_ABR}_lock"
 CONF_DIR="$ROOT_DIR/etc/config"
-ifconfig ppp0 >/dev/null 2>/dev/null && WAN_IF='ppp0' || WAN_IF="$(/bin/nvram get wan_ifname)"
+ifconfig ppp0 && WAN_IF='ppp0' || WAN_IF="$(/bin/nvram get wan_ifname)"
 # VPN tunnel detection
-if ifconfig wg0 >/dev/null 2>/dev/null; then
+if ifconfig wg0; then
   # WireGuard
   TUN_IF='wg0'
 else
   TUN_IF="$(ps -w|/bin/grep -F -- '/usr/sbin/openvpn --dev'|/bin/grep -vE 'grep|server_tap|server_tun')"
   [ "$TUN_IF" ] && TUN_IF=${TUN_IF##* --dev } && TUN_IF=${TUN_IF%% *} # Open VPN client or no tunneling
 fi
+STDERR=/dev/null
+} >/dev/null 2>&1
 
 # INFO FROM (2 bits)
 INFO_FROM_MASK=3
@@ -114,14 +117,12 @@ INFO_LOGD_MASK=3
 
 sc_conf() { [ -z "$2" ] && _OPT= || _OPT=".$2" ;/sbin/uci -qc $CONF_DIR $1 $SC_ABR$_OPT; return $?; }
 
-get_ipt() 2>/dev/null _IPT="$($IPT_BIN -S|/bin/grep -F "$SC_ABR")"
+get_ipt() 2>>"$STDERR" _IPT="$($IPT_BIN -S|/bin/grep -F "$SC_ABR")"
 
 inet_for_if() {
   _IP="$(/usr/sbin/ip -4 addr show $1|/usr/bin/awk 'NR==2 {print $2;exit}')"
-  if [ "$IPR_BIN" ]
-    then echo $_IP|iprange -
-    else _IP=$(/bin/ipcalc.sh $_IP|/usr/bin/awk -F= '/NETWORK|PREFIX/ {ORS="/";print $2}');echo ${_IP%?}
-  fi
+  if [ "$IPR_BIN" ]; then echo $_IP|iprange -
+  else _IP=$(/bin/ipcalc.sh $_IP|/usr/bin/awk -F= '/NETWORK|PREFIX/ {ORS="/";print $2}');echo ${_IP%?}; fi
 }
 
 # ---------------------------------------------
@@ -137,6 +138,8 @@ if [ "$STDERR" ]; then DEBUG=true
   sc_conf show | /usr/bin/awk '{print "   - "$0}' >>"$STDERR"
 else DEBUG=false STDERR=/dev/null
 fi
+
+_exit() { $DEBUG && debug "exiting with code: $1"; exit $1; }
 
 # -------------- LOGD FUNCTIONS ---------------
 # Aegis logging daemon
@@ -319,7 +322,7 @@ shield_uprear() { $DEBUG && debug "|---> shield_uprear $*"
       NFO_IPS=$((NFO_IPS+INFO_IPS_BL_LOAD))
     else
     # no netset file, exiting with _IPS=0
-      exit 1
+      _exit 1
     fi
   fi
   
@@ -469,10 +472,7 @@ shield_uprear() { $DEBUG && debug "|---> shield_uprear $*"
 ###############################################
 
 #we are called from firewall_start.sh
-if [ "$1" == "_fws" ]; then
-  sc_conf get up >/dev/null && shield_uprear "$INFO_FROM_FWS"
-  $DEBUG && debug "exiting with no error"; exit 0
-fi
+if [ "$1" == "_fws" ]; then sc_conf get up >/dev/null && shield_uprear "$INFO_FROM_FWS"; _exit 0; fi
 
 #when called from post-mount.sh
 _pm() { $DEBUG && debug "_pm $*"
@@ -480,7 +480,7 @@ _pm() { $DEBUG && debug "_pm $*"
     [ -d "$ROOT_DIR" ] || /bin/ln -sfn /tmp/mnt/$2/bolemo $ROOT_DIR
     sc_init; shield_init; shield_uprear "$INFO_FROM_PM"
   fi
-  $DEBUG && debug "exiting with no error"; exit 0
+  _exit 0
 }
 
 ###############################################
@@ -576,8 +576,8 @@ clean_postmount() { $DEBUG && debug "clean_postmount"
 
 # SYMLINK: /usr/bin/SELF ######################
 check_path() { $DEBUG && debug "check_path"
-  command -v "$SC_NAME" > /dev/null && return 0 || return 1
-}
+  return command -v "$SC_NAME"
+} >/dev/null
 
 set_path() { $DEBUG && debug "set_path"
   [ -e "/usr/bin/$SC_NAME" ] || /bin/ln -s "$SC_NICEPATH" "/usr/bin/$SC_NAME"
@@ -648,10 +648,10 @@ echo "- Downloading:"
     echo -ne "\033[0m"
     >&2 echo -e "\033[31m! Wget error code $?! Could not download $DL_PATH\033[0m"
     /bin/rm -f "$DL_PATH"
-    exit 1
+    _exit 1
   fi
   check_web && install_web
-  exit 0
+  _exit 0
 }
 
 _upgrade() { $DEBUG && debug "_upgrade"
@@ -679,7 +679,7 @@ upgrade() { $DEBUG && debug "upgrade"
       fi
     else
       >&2 echo -e "\033[31m! Could not check what is the latest version online!\033[0m"
-      exit 1
+      _exit 1
     fi
     UPGRADE_URL="$SC_MAIN_REPO/$SC_NAME"
     UPGRADE_VER="$SC_LAST_VERS"
@@ -694,14 +694,14 @@ upgrade() { $DEBUG && debug "upgrade"
 # get default sources list (from bolemo github)
 get_def_srclst() { $DEBUG && debug "get_def_srclst"
   if [ ! -s "$SRC_LIST" ]; then
-    [ "$VERBOSE" ] && echo -e "! $SRC_LIST is missing or empty!"
+    [ $VERBOSE ] && echo -e "! $SRC_LIST is missing or empty!"
     SRC_LIST_URL="$SC_MAIN_REPO/$SC_NAME.sources"
     if /usr/bin/wget -qO "$SRC_LIST" --no-check-certificate "$SRC_LIST_URL"; then
-      [ "$VERBOSE" ] && echo -e "- Default list was downloaded."
+      [ $VERBOSE ] && echo -e "- Default list was downloaded."
     else
       >&2 echo -e "\033[31m! Wget error code $?! Could not download $SRC_LIST_URL\033[0m"
       /bin/rm -f "$SRC_LIST"
-      exit 1
+      _exit 1
     fi
   fi
 }
@@ -742,7 +742,7 @@ install_web() { $DEBUG && debug "install_web"
     echo -ne "\033[0m"
     >&2 echo -e "\033[31m! Wget error code $?! Could not download $DL_PATH\033[0m"
     /bin/rm -f "$DL_PATH"
-    exit 1
+    _exit 1
   fi
   echo -ne "\033[35m"
   if /usr/bin/wget -qO "$DL_PATH" $_PROG "${UPGRADE_URL}_web.cgi"; then
@@ -754,14 +754,14 @@ install_web() { $DEBUG && debug "install_web"
     echo -ne "\033[0m"
     >&2 echo -e "\033[31m! Wget error code $?! Could not download $DL_PATH\033[0m"
     /bin/rm -f "$DL_PATH"
-    exit 1
+    _exit 1
   fi
   if ! check_web; then
     /bin/rm -f "/www/bolemo" 2>/dev/null
     /bin/ln -sfn "$WWW_PATH" '/www/bolemo' 2>/dev/null
     echo "- $WEB_NAME paths were repaired."
   fi
-  exit 0
+  _exit 0
 }
 
 clean_web() { $DEBUG && debug "clean_web"
@@ -1281,7 +1281,7 @@ _status >/dev/null
     [ $((_WN&WN_LOG_DIFF)) -ne 0 ] && echo -e "\033[35m- current logging settings differs from last time shield was upreared.\033[0m"
   fi
  
-  [ "$VERBOSE" ] || return 0
+  [ $VERBOSE ] || return 0
 
   echo -ne '\033[1;36mDetailed status:\033[0m'; [ "$VERBOSE" -ge 2 ] && echo " (CODE: $_CK)" || echo ''
   echo "- Active WAN interface is '$WAN_IF'."
@@ -1427,11 +1427,11 @@ _status >/dev/null
       ipset -L -t $_SET|/bin/sed 's/^/- /'
     done
   fi
-  exit $_RETVAL
+  _exit $_RETVAL
 }
 
 status_raw() { $DEBUG && debug "status_raw"
-  echo "$(_status) '$WAN_IF' '$TUN_IF'"; $DEBUG && debug "exiting with no error"; exit 0
+  echo "$(_status) '$WAN_IF' '$TUN_IF'"; _exit 0
 }
 #---------------------------- END _STATUS ----------------------------
 
@@ -1479,7 +1479,7 @@ echo -e "\033[1;36m$SC_NAME $SC_VERS\033[0m"'
 #    MAIN ROUTINE
 #
 ###############################################
-[ $# = 0 ] && { >&2 echo -e "\033[31m! No parameter!\033[0m"; print_help; exit 1; }
+[ $# = 0 ] && { >&2 echo -e "\033[31m! No parameter!\033[0m"; print_help; _exit 1; }
 [ "$1" = "_pm" ] && [ "$2" ] && _pm # Called from post-mount.sh, go to right processing...
 
 ARGS=" $* "
@@ -1508,9 +1508,9 @@ fi
 
 PARAM="$(echo "$ARGS" | /bin/sed 's/-[[:alpha:]=]*[[:space:]]*[[:digit:]]*//g')"
 case $(echo "$PARAM"|/usr/bin/wc -w) in
-  0) >&2 echo -e "\033[31m! No parameter!\033[0m"; print_help; exit 1 ;;
+  0) >&2 echo -e "\033[31m! No parameter!\033[0m"; print_help; _exit 1 ;;
   1) PARAM="$(echo "$PARAM"|/bin/sed 's/ //g')" ;;
-  *) >&2 echo -e "\033[31m! Too many parameters!\033[0m"; print_help; exit 1 ;;
+  *) >&2 echo -e "\033[31m! Too many parameters!\033[0m"; print_help; _exit 1 ;;
 esac
 
 if [ -z "${ARGS##* -q *}" ]; then QUIET=1; else
@@ -1581,7 +1581,7 @@ case "$PARAM" in
   '_down') VERBOSE=1; shield_down ;;
   '_upgrade') _upgrade ;;
   
-  *) >&2 echo -e "\033[31m! Unknown Parameter $2!\033[0m"; print_help; exit 1 ;;
+  *) >&2 echo -e "\033[31m! Unknown Parameter $2!\033[0m"; print_help; _exit 1 ;;
 esac
 
-$DEBUG && debug "end of script, exiting with no error"; exit 0
+_exit 0
