Update firewall-blocklist

diff --git a/firewall-blocklist b/firewall-blocklist
--- a/firewall-blocklist
+++ b/firewall-blocklist
@@ -64,14 +64,26 @@ FWS_DIR="/opt/scripts"
 FWS_FILE="$FWS_DIR/firewall-start.sh"
 
 upgrade() {
-  [ $VERBOSE ] && echo -e "\033[1;36mUpgrading:\033[0m\n- Downloading latest version:"
+  [ $VERBOSE ] && echo -e "\033[1;36mUpgrading:\033[0m"
+  [ $VERBOSE ] && echo -ne "- Checking latest available version...\r"
+  SC_LAST_VERS="$(last_avail_version)";
+  if [ $SC_LAST_VERS ]
+    then if [ $SC_VERS = $SC_LAST_VERS ]
+      then [ $VERBOSE ] && { echo "- This is already the last version.        "; exit 0; }
+      else [ $VERBOSE ] && echo "- New version found: $SC_LAST_VERS       "
+    fi
+    else
+      >&2 echo -e "\033[31m! Could not check what is the last version online!\033[0m"
+      exit 1
+  fi
+  [ $VERBOSE ] && echo "- Downloading:"
   UPGRADE_URL="https://raw.githubusercontent.com/bolemo/firewall-blocklist/master/firewall-blocklist"
   DL_PATH="/tmp/$SC_NAME.dl"
   [ $VERBOSE ] && { _PROG='--show-progress'; echo -ne "\033[35m"; } || _PROG=''
   if wget -qO "$DL_PATH" $_PROG "$UPGRADE_URL"; then
     \mv "$DL_PATH" "$SC_NICEPATH"
     chmod +x "$SC_NICEPATH"
-    [ $VERBOSE ] && echo -e "\033[0m- Script installed to $SC_NICEPATH" || echo 'Done.'
+    [ $VERBOSE ] && echo -e "\033[0m- Script installed to $SC_NICEPATH"
   else
     [ $VERBOSE ] && echo -ne "\033[0m"
     >&2 echo -e "\033[31m! Wget error code $?! Could not download $DL_PATH\033[0m"
