Update firewall-blocklist

diff --git a/firewall-blocklist b/firewall-blocklist
--- a/firewall-blocklist
+++ b/firewall-blocklist
@@ -68,12 +68,14 @@ if [ $1 ] && [ $1 = "upgrade" ]; then
   echo "- Downloading latest version:"
   UPGRADE_URL="https://raw.githubusercontent.com/bolemo/firewall-blocklist/master/firewall-blocklist"
   DL_PATH="/tmp/$SC_NAME.dl"
+  echo -ne "\033[35m"
   if wget -qO "$DL_PATH" --show-progress "$UPGRADE_URL"; then
     \mv "$DL_PATH" "$SC_NICEPATH"
     chmod +x "$SC_NICEPATH"
-    echo "- Script installed."
+    echo -e "\033[0m- Script installed."
   else
-    >&2 echo "- Could not download the script; wget returned $?"
+    echo -ne "\033[0m"
+    >&2 echo -e "- \033[31mCould not download the script; wget returned $?\033[0m"
     rm -f "$DL_PATH"
     exit 1
   fi
