Update firewall-blocklist

diff --git a/firewall-blocklist b/firewall-blocklist
--- a/firewall-blocklist
+++ b/firewall-blocklist
@@ -62,26 +62,24 @@ TMP_FILE="$IP_LIST.tmp"
 FWS_DIR="/opt/scripts"
 FWS_FILE="$FWS_DIR/firewall-start.sh"
 
-#upgrade
-if [ $1 ] && [ $1 = "upgrade" ]; then
-  echo -e "\033[1;36mUpgrading:\033[0m"
-  echo "- Downloading latest version:"
+upgrade() {
+  [ $VERBOSE ] && echo -e "\033[1;36mUpgrading:\033[0m\n- Downloading latest version:"
   UPGRADE_URL="https://raw.githubusercontent.com/bolemo/firewall-blocklist/master/firewall-blocklist"
   DL_PATH="/tmp/$SC_NAME.dl"
-  echo -ne "\033[35m"
-  if wget -qO "$DL_PATH" --show-progress "$UPGRADE_URL"; then
+  [ $VERBOSE ] && { _PROG='--show-progress'; echo -ne "\033[35m"; } || _PROG=''
+  if wget -qO "$DL_PATH" $_PROG "$UPGRADE_URL"; then
     \mv "$DL_PATH" "$SC_NICEPATH"
     chmod +x "$SC_NICEPATH"
-    echo -e "\033[0m- Script installed to $SC_NICEPATH"
+    [ $VERBOSE ] && echo -e "\033[0m- Script installed to $SC_NICEPATH" || echo 'Done.'
   else
-    echo -ne "\033[0m"
-    >&2 echo -e "- \033[31mWget error code $?! Could not download $DL_PATH\033[0m"
+    [ $VERBOSE ] && echo -ne "\033[0m"
+    >&2 echo -e "\033[31m! Wget error code $?! Could not download $DL_PATH\033[0m"
     rm -f "$DL_PATH"
     exit 1
   fi
     
   exit 0
-fi
+}
 
 check_firewall_start() {
   [ -x $FWS_FILE ] || return 1
@@ -108,18 +106,21 @@ count_ip_in_ipset() {
   ipset list $1 | sed -n '/Members:/,$p' | tail -n +2 | grep -oE '(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\/([0-9]{1,2})' | awk -F / '{ count[$2]++ } END { for (mask in count) total+=count[mask]*2^(32-mask); print total }'
 }
 
-test() {
+info() {
   echo -e "\033[1;36mTest:\033[0m"
   if [ -r "$SRC_LIST" ] && [ -d $(dirname "$IP_LIST") ] && [ -d $(dirname "$TMP_FILE") ];
     then echo "- The script is properly installed."
-    else echo -e "- \033[35mSomething is wrong with installation!\033[0m"
+    else echo -e "\033[31m! Something is wrong with installation!\033[0m"
   fi
   echo "- $SC_NAME version: $SC_VERS"
   echo -ne "- Checking latest available version...\r"
   SC_LAST_VERS="$(last_avail_version)";
-  if [ $SC_LAST_VERS ] && [ $SC_VERS = $SC_LAST_VERS ]
-    then echo "- This is the last known version.       "
-    else echo -e "- \033[35mLast version available\033[0m: $SC_LAST_VERS       "
+  if [ $SC_LAST_VERS ]
+    then if [ $SC_VERS = $SC_LAST_VERS ]
+      then echo "- This is the last version.       "
+      else echo -e "\033[35m- Lastest version available: $SC_LAST_VERS       \033[0m"
+    fi
+    else echo -e "\033[31m! Could not check what is the last version online!\033[0m"
   fi
 }
 
@@ -130,7 +131,7 @@ init() {
     [ $VERBOSE ] && echo "- $FWS_FILE is in place and ok"
   else
     create_firewall_start
-    check_firewall_start || { >&2 echo "Problem with $FWS_FILE!"; exit 1; }
+    check_firewall_start || { >&2 echo -e "\033[31m! Problem with $FWS_FILE!\033[0m"; exit 1; }
     [ $VERBOSE ] && echo "- $FWS_FILE was edited and is now ok."
   fi
   /usr/sbin/net-wall restart > /dev/null
@@ -159,7 +160,7 @@ clean() {
 }
 
 set_ipset() {
-  [ -r $IP_LIST ] || { >&2 echo "$IP_LIST not readable!"; exit 1; }
+  [ -r $IP_LIST ] || { >&2 echo -e "\033[31m! $IP_LIST not readable!\033[0m"; exit 1; }
 
   if [ $VERBOSE ]; then
     MAX="$(wc -l < $IP_LIST)"
@@ -175,7 +176,7 @@ set_ipset() {
 
 update_iplist() {
   [ $VERBOSE ] && echo -e "\033[1;36mUpdating blocklist from sources...\033[0m"
-  [ -r $SRC_LIST ] || { >&2 echo "$SRC_LIST not readable!"; exit 1; }
+  [ -r $SRC_LIST ] || { >&2 echo -e "\033[31m! $SRC_LIST not readable!\033[0m"; exit 1; }
 
   :>"$TMP_FILE"
   # Process each source url
@@ -189,10 +190,10 @@ update_iplist() {
       { { { { wget $WGET_OPTS "$URL"; echo $? >&3; } | grep '^[0-9]' | sed -e 's/;.*//' >>"$TMP_FILE"; } 3>&1; } | { read _EC; exit $_EC; } } 4>&1
       _EC=$?
       [ $VERBOSE ] && echo -e "\033[0m"
-      [ $_EC = 0 ] && _NBOK=$((_NBOK+1)) || >&2 echo "Wget error code $_EC! Could not download $URL"
+      [ $_EC = 0 ] && _NBOK=$((_NBOK+1)) || >&2 echo -e "\033[31m! Wget error code $_EC! Could not download $URL\033[0m"
     done
-    [ $_NBOK = 0 ] && { >&2 echo "Could not get any list!"; rm "$TMP_FILE"; exit 1; }
-    [ $_NBOK = $_TOT ] || >&2 echo "Downloaded only $_NBOK / $_TOT list(s)!"
+    [ $_NBOK = 0 ] && { >&2 echo -e "\033[31m! Could not get any list!\033[0m"; rm "$TMP_FILE"; exit 1; }
+    [ $_NBOK = $_TOT ] || >&2 echo -e "\033[31m! Downloaded only $_NBOK / $_TOT list(s)!\033[0m"
   }
   [ $VERBOSE ] && echo "- Removing duplicates..."
   sort "$TMP_FILE" | uniq > "$IP_LIST"
@@ -258,18 +259,19 @@ print_help() {
   echo -e " \033[1;35mupdate_only\033[0m - generates $IP_LIST from servers in $SRC_LIST"
   echo -e " \033[1;35mupdate\033[0m      - update_only then load_set [probably what you want to use]"
   echo -e " \033[1;35mstatus\033[0m      - display status"
-  echo -e " \033[1;35mtest\033[0m        - check if this script is installed properly"
+  echo -e " \033[1;35minfo\033[0m        - check if this script is installed properly"
+  echo -e " \033[1;35mupgrade\033[0m     - download and install latest version"
   echo -e " \033[1;35mhelp\033[0m        - display this"
   echo -e "\033[7mOptions:\033[0m"
   echo -e " \033[1;36m-v\033[0m          - verbose mode"
 }
 
 # Main routine
-[ $# = 0 ] && { >&2 echo "No parameter!"; print_help; exit 1; }
+[ $# = 0 ] && { >&2 echo -e "\033[31m! No parameter!\033[0m"; print_help; exit 1; }
 
 if [ "$1" != "_niced" ]; then
   if [ "$1" = "-v" ]; then
-    [ $# = 1 ] && { >&2 echo "No parameter!"; print_help; exit 1; }
+    [ $# = 1 ] && { >&2 echo -e "\033[31m! No parameter!\033[0m"; print_help; exit 1; }
     PARAM="$2"; VERB="_verbose"
   elif [ $# = 2 ] && [ "$2" = "-v" ]; then
     PARAM="$1"; VERB="_verbose"
@@ -291,8 +293,9 @@ case $2 in
   "update") init; update_iplist; set_ipset; [ $VERBOSE ] && status ;;
   "status") status ;;
   "help") print_help ;;
-  "test") test ;;
-  *) >&2 echo "Unknown Parameter $2!"; print_help; exit 1 ;;
+  "info") info ;;
+  "upgrade") upgrade ;;
+  *) >&2 echo -e "\033[31m! Unknown Parameter $2!\033[0m"; print_help; exit 1 ;;
 esac
 
 exit 0
